name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Descargar el código del repositorio
    - uses: actions/checkout@v4

    # Paso 2: Instalar g++ y otras dependencias
    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    # Paso 3: Compilar el proyecto con g++
    - name: Compile with g++
      run: g++ main.cpp SortingProgram.cpp -o sorting_program

    # Paso 4: (Opcional) Ejecutar el programa compilado
    - name: Run the program
      run: |
        echo -e "1\n3\n2\n1\n4\n2\n1\n5\n2\n1\n6\n2\n1\n7\n2\n1\n8\n2\n9" | ./sorting_program